// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql_generated

import (
	"database/sql"
	"time"
)

type Blog struct {
	ID        string
	Title     string
	Content   string
	TagID     sql.NullString
	Author    string
	CreatedAt time.Time
}

type Tag struct {
	ID   string
	Name string
}

type User struct {
	ID    string
	Name  string
	Email string
}
