// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sql_generated

import (
	"context"
	"database/sql"
	"time"
)

const countBlogs = `-- name: CountBlogs :one
SELECT COUNT(*) FROM blogs
`

func (q *Queries) CountBlogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllBlog = `-- name: GetAllBlog :many
SELECT b.id, b.title, b.content, b.tag_id, b.author, b.created_at, t.name as tag_name
FROM blogs b
LEFT JOIN tags t ON b.tag_id = t.id
ORDER BY b.created_at DESC
`

type GetAllBlogRow struct {
	ID        string
	Title     string
	Content   string
	TagID     sql.NullString
	Author    string
	CreatedAt time.Time
	TagName   sql.NullString
}

func (q *Queries) GetAllBlog(ctx context.Context) ([]GetAllBlogRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllBlog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllBlogRow
	for rows.Next() {
		var i GetAllBlogRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.TagID,
			&i.Author,
			&i.CreatedAt,
			&i.TagName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlogByID = `-- name: GetBlogByID :one
SELECT b.id, b.title, b.content, b.tag_id, b.author, b.created_at, t.name as tag_name
FROM blogs b
LEFT JOIN tags t ON b.tag_id = t.id
WHERE b.id = ?
`

type GetBlogByIDRow struct {
	ID        string
	Title     string
	Content   string
	TagID     sql.NullString
	Author    string
	CreatedAt time.Time
	TagName   sql.NullString
}

func (q *Queries) GetBlogByID(ctx context.Context, id string) (GetBlogByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBlogByID, id)
	var i GetBlogByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.TagID,
		&i.Author,
		&i.CreatedAt,
		&i.TagName,
	)
	return i, err
}

const getBlogsPaginated = `-- name: GetBlogsPaginated :many
SELECT b.id, b.title, b.content, b.tag_id, b.author, b.created_at, t.name as tag_name
FROM blogs b
LEFT JOIN tags t ON b.tag_id = t.id
ORDER BY b.created_at DESC
LIMIT ? OFFSET ?
`

type GetBlogsPaginatedParams struct {
	Limit  int64
	Offset int64
}

type GetBlogsPaginatedRow struct {
	ID        string
	Title     string
	Content   string
	TagID     sql.NullString
	Author    string
	CreatedAt time.Time
	TagName   sql.NullString
}

func (q *Queries) GetBlogsPaginated(ctx context.Context, arg GetBlogsPaginatedParams) ([]GetBlogsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlogsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlogsPaginatedRow
	for rows.Next() {
		var i GetBlogsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.TagID,
			&i.Author,
			&i.CreatedAt,
			&i.TagName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO tags (id, name) VALUES (?, ?) 
ON CONFLICT(name) DO UPDATE SET name = name
RETURNING id, name
`

type GetOrCreateTagParams struct {
	ID   string
	Name string
}

func (q *Queries) GetOrCreateTag(ctx context.Context, arg GetOrCreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateTag, arg.ID, arg.Name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const storeBlog = `-- name: StoreBlog :one
INSERT INTO blogs (id, title, content, tag_id, author, created_at) VALUES (?, ?, ?, ?, ?, ?) RETURNING id, title, content, tag_id, author, created_at
`

type StoreBlogParams struct {
	ID        string
	Title     string
	Content   string
	TagID     sql.NullString
	Author    string
	CreatedAt time.Time
}

func (q *Queries) StoreBlog(ctx context.Context, arg StoreBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, storeBlog,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.TagID,
		arg.Author,
		arg.CreatedAt,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.TagID,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}
